### ISSUE TITLE
No autofill by value

### ISSUE THREAD

**Issue by forstjiri** [razzbee/tagcomplete#10]
Hi, autocomplete works great and is easy to use, but i got trouble.

I have an input with value like `value="qwe, asd"`.

But when i init `.tagComplete` it does not prefill those values, is this feature missing? 

Thanks.

**Comment by razzbee** [comment]
I willl check it and provide an update, Thanks for the bug

**Comment by forstjiri** [comment]
So far i did add this little code on line 440, seems to work, did not test much.
```JS
var tags = userInput.val().split(options.tokenizer);
            if(tags[0]) {
				$.each(tags, function (key, val) {
					$.fn.addTag(val,val, instanceData);
				});
            }
```

**Comment by razzbee** [comment]
I have added the prefilled and fixed extra css bugs, kindly check the example.html file for implementation. and thanks for the patience
