### ISSUE TITLE
freeInput option not working?

### ISSUE THREAD

**Issue by blubbll** [razzbee/tagcomplete#2]
in the options i did

                freeInput: false,
                freeEdit: false,

but i can still click and remove the tags that i enter.

**Comment by razzbee** [comment]
It should work, can you provide your own example

**Comment by blubbll** [comment]
https://codepen.io/Blubbll/pen/pORRQB i think i misunderstood the config.
i just don't want the input to appear in the suggestion list.

edit: i put freeInput in the wrong scope (i put it into the autosuggest options)

**Comment by razzbee** [comment]
So I guess you are okay now?

**Comment by blubbll** [comment]
Well yes. Thanks
